# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :pushTestflight do

    build_number = latest_testflight_build_number(app_identifier: "com.app.Calibrr") + 1
    increment_build_number(build_number: build_number, xcodeproj: "Calibrr.xcodeproj")

		disable_automatic_code_signing(path: "Calibrr.xcodeproj")

    # build_app(workspace: "Calibrr.xcworkspace", scheme: "Calibrr")
    # upload_to_testflight

		gym(
  		scheme: "Calibrr",
			workspace: "Calibrr.xcworkspace",
    	configuration: "Release",
    	export_method: "app-store",
			include_bitcode: false,
			include_symbols: true
		)

    testflight()

  end

  desc "Testflight2"
  lane :improvedTestflight do

    version_number = get_version_number(xcodeproj: "Calibrr.xcodeproj", target: "Calibrr")
		build_number = latest_testflight_build_number(app_identifier: "com.app.Calibrr") + 1

		increment_build_number(build_number: build_number,xcodeproj: "Calibrr.xcodeproj")

		create_keychain(
      		name: ENV["MATCH_KEYCHAIN_NAME"],
      		password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      		default_keychain: true,
      		unlock: true,
      		timeout: 3600,
      		add_to_search_list: true
    	)

		match(
			type: "appstore",
			app_identifier: "com.app.Calibrr",
  		keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
  		keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
			readonly: true
		)

		disable_automatic_code_signing(path: "Calibrr.xcodeproj")

		gym(
  		scheme: "Calibrr",
			workspace: "Calibrr.xcworkspace",
    	configuration: "Release",
    	export_method: "app-store",
			include_bitcode: false,
			include_symbols: true
		)

		changelog = read_changelog()

		testflight(changelog: changelog)

		stamp_changelog(section_identifier: "#{version_number}")

  end

end
