platform :ios, '13.0'

target 'Calibrr' do
  inhibit_all_warnings!
  use_frameworks!

  # UI
  pod 'SnapKit'
  pod 'MaterialComponents/Buttons'
  pod 'TTRangeSlider'

  # Networking
  pod 'JWTDecode'
  pod 'PromiseKit/Alamofire'


  # Other
  
  pod 'SwiftKeychainWrapper'
  pod 'ReachabilitySwift'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'NVActivityIndicatorView'
  pod 'NVActivityIndicatorView/Extended'
  pod 'TwitterKit'
  pod 'FBSDKLoginKit'
  pod 'LinkedinSwift'
  pod 'Toast-Swift'
  pod 'SwiftyStoreKit'
  pod 'OpenAPIClient', :path => 'Calibrr/generated/OpenAPIClient.podspec'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.6'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
